### ISSUE TITLE
Add Column

### ISSUE THREAD

**Issue by fullstuckdevelper** [FirstBitDevelopment/RD-Check-List#1]
Plaese add column ProductCode from Products TPV Stcok table
show attachment
![RD](https://user-images.githubusercontent.com/78589792/217838271-1dde9650-b386-48bc-9ef2-189d22fa36ce.JPG)

**Comment by sdktraceur** [comment]
It reflects the entire solution performance.
Some model doesn't have this field at all.

**Comment by sdktraceur** [comment]
![image](https://user-images.githubusercontent.com/60514256/219972737-527af439-628b-4330-b25a-9b7e84bdd12f.png)
